# Generated by Django 2.0.1 on 2018-03-10 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0002_auto_20180310_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='author',
        ),
        migrations.AddField(
            model_name='myhouses',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='authors',
        ),
    ]
