# Generated by Django 2.0.1 on 2018-03-12 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_auto_20180310_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhouses',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_rent',
            field=models.IntegerField(null=True),
        ),
    ]
